### ISSUE TITLE
Custom add-to-cart logic and "handoff" to the UltraCart's cart page

### ISSUE THREAD

**Issue by milanstosic** [UltraCart/rest_api_v2_sdk_php#21]
Hello,

I'm trying to develop a custom PHP solution for the add-to-cart for my client's website and I managed to use API to add items to the cart. However, I don't know how to "transfer" user from our website to the UltraCart's cart page (if that's even possible - not the checkout, but to the cart page because there's some additional information for the user that they can pick before they continue to the checkout).

I found [this example](https://github.com/UltraCart/rest_api_v2_sdk_php/blob/master/docs/Api/CheckoutApi.md), but I get the following error:
"Exception when calling CheckoutApi->handoffCart: [400] Client error: `POST https://secure.ultracart.com/rest/v2/checkout/cart/handoff` resulted in a `400 Bad Request` response: Server side object 'cart' could not be constructed from the json you provided."

So, 2 things:
1. Is this the method that I should use - or this method is just for the checkout handoff
2. is there something else that I should do in order to prepare the data for this method (I assume that I need to add cart_id somehow, maybe even some other info)

**Comment by ucjonathan** [comment]
@milanstosic You need to fully populate the CheckoutHandoffRequest object before making the API call.  If you look under Configuration -> Development -> Authorized Applications -> Log you can see the full request/response that you're sending up for your API calls including the error message.  The error about the cart was because your request was just an empty object.  You populated that with a cart that only contained the cart id and then the next error you're receiving is due to no operation being specified.  The operation is documented on the CheckoutHandoffRequest object:

![image](https://user-images.githubusercontent.com/5116030/123258802-cabb9600-d4c1-11eb-92b2-3d969d695a6e.png)

**Comment by milanstosic** [comment]
Hi,

Sorry for late reply. I just wanted to say thank you because I managed to understand where I made a mistake earlier and how to organize everything better.

I totally missed that 'operaton' object.
