### ISSUE TITLE
Unable to filter out orders based on current_stage

### ISSUE THREAD

**Issue by him-developer** [UltraCart/rest_api_v2_sdk_php#4]
Hello Perry,

Got one more issue.
We are unable to filter order based on current_stage parameter.
Below is the code which giving us empty array and we definitely have rejected orders in database.
   
     ///REGUALR ORDERS 
      $data["_expand"] = 'summary, payment, payment.transaction';
      $data["_limit"] = 200;
      $data["current_stage"] = "Rejected";
      $data["_sort"] = '-order_id';
     
      
      $uri = PATH.'/order/orders?'.http_build_query($data) ;
      $result = \Httpful\Request::get($uri)                  // Build a GET request...
      ->addHeader('X-UltraCart-Api-Version', API_VER) 
      ->addHeader('x-ultracart-simple-key',SIMPLE_KEY)
      ->addHeader('cache-control', 'no-cache') 
      ->send();

**Comment by perrytew** [comment]
Him,
Hello.  It's a bug.  The API documentation has the full names of the stages, while the implementation is structuring the query based on the 2-3 character codes.  ("CO" instead of "Completed Order"). 

I've submitted a patch to have the query work with both.  
If you change "Rejected" to "REJ", you should get results.  But, the API will work properly with both by the end of today.

Thank you for finding and alerting us to this bug.
Regards,
Perry
