### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by chadhakavita** [UltraCart/rest_api_v2_sdk_php#9]
Hey perry,

I'm getting Fatal Error. Please have a look.

Fatal error: Uncaught RuntimeException: GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler. in /xxx/xxxx/xxxxx/vendor/guzzlehttp/guzzle/src/functions.php:119 Stack trace: #0 /xxx/xxxx/xxxxx/vendor/guzzlehttp/guzzle/src/HandlerStack.php(40): GuzzleHttp\choose_handler() #1 /xxxx/xxxx/xxxxx/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create() #2 /xxxx/xxxxx/xxxxx/sync_new.php(25): GuzzleHttp\Client->__construct(Array) #3 {main} thrown in /xxxx/xxxxx/xxxxx/vendor/guzzlehttp/guzzle/src/functions.php on line 119

**Comment by ryanjkelly** [comment]
It looks like cURL isn't configured on your server. I recommend contacting your hosting provider to ask them if they can enable it.

**Comment by chadhakavita** [comment]
Hey Ryan,
Okay, Now I've enabled the CURL but this time I'm getting following error:
Fatal error: Interface 'Psr\Http\Message\RequestInterface' not found in /xxx/xxxx/xxxx/vendor/guzzlehttp/psr7/src/Request.php on line 12

**Comment by ryanjkelly** [comment]
I don't have much information, but I have a couple guesses:

1. This could be due to missing or conflicting dependencies. Does your manifest file (`composer.json`) list any packages other than UltraCart's `rest_api_v2_sdk_php`?

2. This could be from a PHP version conflict. Normally, composer will warn you, or even abort the installation process, if it detects that your PHP version doesn't meet the requirements of the packages being installed. However, if you run a composer install locally, then upload it, your local environment's PHP version could meet package requirements, but your remote server could not. That's why it's best to make sure your local and remote environments match up as close as possible.

A couple troubleshooting steps you could try:

1. Wipe your `/vendor` directory and reinstall.

2. If you have other packages listed in your `composer.json` file, try starting a separate project with `rest_api_v2_sdk_php` being the only package, and see if you can successfully call a simple method, like `getItemByMerchantItemId`.

https://github.com/UltraCart/rest_api_v2_sdk_php/blob/master/docs/Api/ItemApi.md#getitembymerchantitemid

**Comment by chadhakavita** [comment]
Thanks Ryan :)
